### ISSUE TITLE
Allow for customized version of Greenlight?

### ISSUE THREAD

**Issue by einhirn** [ebbba-org/ansible-role-bigbluebutton#138]
We're running a customized version of Greenlight - some UI changes, specific localization changes etc.

Do you think this playbook should allow for a custom image via config? If so, do we need to have that image in the public registry or can we have a private one? Also: Should we allow for `docker load/save`-style? 

If you don't think this is used often, I'd need to keep track of a local patch. Doable but not great...

**Comment by BrutalBirdie** [comment]
Hmmm this is a very specific use-case.
I can understand the need behind that but think this might be out of scope for this role.

If you create a PR for that I am happy to assist.

**Comment by DerDanilo** [comment]
I think that this is a good idea since it should be quit simple to implement.

@einhirn You may create a pull request. Create a var for the image, which should default to the standard greenlight image of course.

This should be the line you're looking for.

https://github.com/ebbba-org/ansible-role-bigbluebutton/blob/c19306826949dd1ec2f754bf65763af207da6209/templates/greenlight/docker-compose.yml.j2#L6
